"use client"

import { useSession} from 'next-auth/react'
import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'tech-force',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = {
    user: {
      name: 'John Doe',
      email: 'john@example.com',
    },
    accessToken: 'sample-access-token',
    expires: '2023-12-31',
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
