"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'tech-force',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname()
  console.log(pathname)

  

  const linkPath = pathname === '/bussines' ? '/' : '/bussines'
  const linkTitle = pathname === '/bussines' ? 'For employees' : 'For Employers'
  console.log(linkPath)

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='ml-auto  flex justify-between w-full'>



          <div>
            <button className='mx-10'>Login</button>
            <button>Register</button>
          </div>

          <Link href={linkPath}>
            <p className='w-32 mx-5'>{linkTitle}</p>
          </Link>

        </nav>
        {children}
      </body>
    </html>
  )
}
